[package]
name = "rustbuster"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
url = "2.5.1"
textwrap = "0.16.1"
reqwest = "0.12.5"
tokio = {version = "1.38.0", features = ["full"]}
indicatif = "0.17.8"